Repository GSM-Conference/CS-Conference, pull requests merged in 2023-09, with the labels that each got.

#1 네트워크 부분 PR
  네트워크/Network.md
Labels: Network

#2 소프트웨어 공학 부분 PR
  소프트웨어 공학/애자일 방법론.md
Labels: SoftwareEngineering

#5 데이터베이스 부분 PR
  데이터베이스/데이터베이스.md
Labels: DataBase

#3 알고리즘 부분 PR
  알고리즘/알고리즘.md
Labels: Algorithm
