Repository GSM-Conference/CS-Conference, pull requests merged in 2023-10, with the labels that each got.

#7 소프트웨어 공학부분 PR
  소프트웨어 공학/소프트웨어 공학.md
Labels: SoftwareEngineering

#8 자료구조 부분 PR
  자료구조/선형구조란?.md
  자료구조/스택.md
Labels: DataStructure

#6 알고리즘 부분 PR
  알고리즘/이진탐색.md
Labels: Algorithm

#9 데이터베이스 부분 PR
  데이터베이스/키.md
Labels: DataBase

#10 운영체제 부분 PR
  운영체제/쓰레드.md
Labels: OS
